"""Public generated bytes resume with literal fills and complete-owner negatives."""

from dataclasses import asdict, replace
import json
import os
from pathlib import Path
import shutil
import subprocess
import sys

import pytest
from openpine_contracts import Finality
from pinelib import RuntimeLanguageContext
from pinelib.request import CanonicalBar, DataFinality
from pinelib.request.snapshots import RequestSource, SnapshotRequestProvider
from pinelib.runtime.metadata import InstrumentContext, TimeframeContext
from pinelib.state.checkpoint import RuntimeCheckpoint, canonical_json, sha
from pinelib.state.digest import AppendOnlyHistory

from backtest_engine import (
    BacktestCallbacks,
    BacktestConfig,
    BacktestEngine,
    Bar,
    JsonResumeStateSerializer,
)
from backtest_engine.errors import ResumeUnsupportedError
from openpine.compile.native_rc6 import NativeRC6CompilerAdapter
from openpine.runtime.generated_backtest import run_generated_backtest
from openpine.runtime.generated_checkpoint import JOURNAL_DOMAIN
from openpine.runtime.rc6_worker_runtime import RC6GeneratedScriptSession
from backtest_engine.core.intent_replay import IntentReplayIdentity

COMPONENT_PINS = {
    "openpine-contracts": "db1745756516b47466756c9c5d38fbbb95595a3b",
    "marketdata-provider": "da6c25c55289cea4cbb9329997c165abc1b2af5e",
    "pine2ast": "eb249402e67199b07e9880fadc14e03fb1651edc",
    "ast2python": "9080ed559e5cd9acbfe1400f284314d2af3f9193",
    "optimizer": "623e2639581d23242109dd47e20f14f799fa7b88",
}
SOURCE = """//@version=6
strategy("bytes bridge")
var float missing = na
var array<float> prices = array.new_float(0)
array.push(prices, close)
requested = request.security("", "", close)
if na(missing) and array.size(prices) == 1 and requested == 100
    strategy.entry("foreign-entry", strategy.long, qty=3)
if array.size(prices) == 3 and requested == 120
    strategy.close("foreign-entry", qty=1, immediately=true)
"""


def inputs():
    rows = [(100, 100), (100, 110), (110, 120), (120, 130)]
    bars = [
        Bar(i * 60000, o, c, o, c, 1, (i + 1) * 60000, Finality.FINAL)
        for i, (o, c) in enumerate(rows)
    ]
    config = BacktestConfig(
        "SOLUSDT",
        "1m",
        0,
        180000,
        mintick=1,
        commission_type="none",
        commission_value=0,
        initial_capital=1000,
        force_close_on_end=False,
        semantic_profile="strict_5x",
        export_resume_state=True,
        early_stop_enabled=True,
        min_equity_stop=1000,
    )
    return config, bars


def head(root):
    executable = shutil.which("git")
    assert executable is not None
    return subprocess.check_output(  # noqa: S603 -- fixed read-only Git query of imported source roots
        [executable, "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()


def descriptor():
    import backtest_engine
    import pinelib

    pins = {
        **COMPONENT_PINS,
        "openpine": head(Path(__file__).resolve().parents[1]),
        "backtest_engine": head(Path(backtest_engine.__file__).resolve().parents[1]),
        "pinelib": head(Path(pinelib.__file__).resolve().parents[1]),
    }
    compiled = NativeRC6CompilerAdapter().compile(
        SOURCE,
        module_name="run02_generated_bytes",
        source_name="generated-bytes.pine",
        producer_commits={name: pins[name] for name in ("pine2ast", "ast2python")},
    )
    assert compiled.success, compiled.errors
    return {
        "artifact": {
            "generated_artifact": compiled.generated_artifact,
            "python_code": compiled.python_code,
        },
        "pins": pins,
        "source": SOURCE,
        "stack_id": sha(pins),
    }


@pytest.mark.parametrize(
    "option", ["calc_on_every_tick", "force_close_on_end", "runtime", "identity-config"]
)
def test_unsupported_owner_context_rejects_before_reset(
    compiled_descriptor, wire, option, monkeypatch
):
    config, bars = inputs()
    owner = session(compiled_descriptor, config)
    changes = (
        {option: True}
        if option in {"calc_on_every_tick", "force_close_on_end"}
        else ({"runtime": object()} if option == "runtime" else {"initial_capital": 999})
    )
    engine = BacktestEngine(replace(config, **changes))
    before = owner.export_state()
    monkeypatch.setattr(
        engine, "_reset_state", lambda: pytest.fail("context mismatch reached reset")
    )
    with pytest.raises(ResumeUnsupportedError):
        run_generated_backtest(engine, owner, bars, resume_state=wire)
    assert owner.export_state() == before


def session(data, config=None):
    config, bars = inputs() if config is None else (config, inputs()[1])
    generated = data["artifact"]["generated_artifact"]
    version = generated["version_context"]
    instrument = InstrumentContext(
        "SOLUSDT",
        "binance:spot:SOLUSDT",
        "BINANCE",
        "USDT",
        "SOL",
        "UTC",
        "crypto",
        1.0,
        1.0,
    )
    source_bars = tuple(
        CanonicalBar(
            instrument.tickerid,
            "1",
            bar.time,
            bar.time_close,
            str(bar.open),
            str(bar.high),
            str(bar.low),
            str(bar.close),
            "1",
            DataFinality.FINAL,
            0,
        )
        for bar in bars
    )
    provider = SnapshotRequestProvider(
        (
            RequestSource(
                instrument.tickerid,
                instrument,
                "spot",
                "1",
                source_bars,
                sha([asdict(bar) for bar in bars]),
            ),
        )
    )
    return RC6GeneratedScriptSession(
        artifact=data["artifact"],
        language=RuntimeLanguageContext(
            int(version["pine_version"]),
            str(version["spec_snapshot_ref"]),
            "pine-v6",
            str(generated["target_manifest_hash"]),
            str(version["origin"]),
        ),
        instrument=instrument,
        timeframe=TimeframeContext.parse("1"),
        identity=IntentReplayIdentity(
            "run02-generated-bytes",
            "bytes-bridge",
            data["stack_id"],
            "strict_5x",
            "binance:spot:SOLUSDT:1m",
            instrument.tickerid,
            "1m",
        ),
        producer_commit=data["pins"]["ast2python"],
        request_provider=provider,
        engine_config=config,
    )


def projection(engine):
    return {
        "fills": [[f.order_id, f.side, f.qty, f.price, f.bar_index] for f in engine.fills],
        "position": [engine.position.direction, engine.position.size, engine.position.avg_price],
        "equity": engine.equity,
        "realized_profit": engine.position.realized_profit,
        "closed_trades": [asdict(trade) for trade in engine.closed_trades],
    }


def producer(data):
    config, bars = inputs()
    engine, owner = BacktestEngine(config), session(data, config)
    tape = []
    result = run_generated_backtest(engine, owner, bars, tape_events=tape)
    assert result.status == "early_stopped"
    assert result.resume_state.bar_index == 0
    state = result.resume_state
    wire = JsonResumeStateSerializer().dumps(state)
    assert state.strategy_state["runtime"]["state"]["requests"]["registry"]["datasets"]
    return wire, tape


def literal_oracle(engine, tape):
    assert [(item["command_id"], item["qty"], item["bar_index"]) for item in tape] == [
        ("close:foreign-entry", "1", 2),
    ]
    assert [(f.side, f.qty, f.price, f.bar_index) for f in engine.fills] == [
        ("buy", 3.0, 100.0, 1),
        ("sell", 1.0, 120.0, 2),
    ]
    assert (engine.position.direction, engine.position.size, engine.position.avg_price) == (
        "long",
        2.0,
        100.0,
    )
    assert engine.equity == 1080.0


@pytest.fixture(scope="module")
def compiled_descriptor():
    return descriptor()


@pytest.fixture
def wire(compiled_descriptor):
    return producer(compiled_descriptor)[0]


def test_public_bytes_continuation_matches_literal_effects_and_control(compiled_descriptor, wire):
    config, bars = inputs()
    owner, engine, tape = session(compiled_descriptor, config), BacktestEngine(config), []
    result = run_generated_backtest(engine, owner, bars, resume_state=wire, tape_events=tape)
    assert result.status == "completed"
    literal_oracle(engine, tape)
    control_config = replace(config, early_stop_enabled=False)
    control, whole = BacktestEngine(control_config), session(compiled_descriptor, control_config)
    full_tape = []
    run_generated_backtest(control, whole, bars, tape_events=full_tape)
    assert projection(engine) == projection(control)
    assert [(item["command_id"], item["qty"], item["bar_index"]) for item in full_tape] == [
        ("foreign-entry", "3", 0),
        ("close:foreign-entry", "1", 2),
    ]
    assert owner.session.semantic_state_hash == whole.session.semantic_state_hash
    assert owner.execution_cursor == whole.execution_cursor


def reseal(state, *, receipts=False):
    original = state["runtime"]
    state["runtime"] = RuntimeCheckpoint.seal(
        original["identity_hash"], original["state"], schema_version=original["schema_version"]
    ).to_dict()
    if receipts:
        state["callback_receipts_identity"] = AppendOnlyHistory(
            JOURNAL_DOMAIN, state["callback_receipts"]
        ).identity()
    state["content_hash"] = sha(
        {key: value for key, value in state.items() if key != "content_hash"}
    )


def mutate(state, fault):
    owner = state.strategy_state
    runtime = owner["runtime"]["state"]
    if fault == "identity":
        owner["identity"]["producer_commit"] = COMPONENT_PINS["pine2ast"]
    elif fault == "na":
        slot = next(slot for slot in runtime["slots"] if slot["committed"] == {"$pine": "na"})
        slot["committed"] = slot["working"] = {"$pine": "foreign-na"}
    elif fault == "refgraph":
        runtime["references"]["objects"][0]["kind"] = "foreign"
    elif fault == "request":
        runtime["requests"]["registry"]["datasets"][0]["child_state"]["compiled-runtime"]["state"][
            "transcript"
        ]["entries"][-1]["state_hash"] = sha("late child forgery")
        child = runtime["requests"]["registry"]["datasets"][0]["child_state"]["compiled-runtime"]
        runtime["requests"]["registry"]["datasets"][0]["child_state"]["compiled-runtime"] = (
            RuntimeCheckpoint.seal(
                child["identity_hash"], child["state"], schema_version=child["schema_version"]
            ).to_dict()
        )
    elif fault == "transcript":
        runtime["transcript"]["entries"][-1]["state_hash"] = sha("late parent forgery")
    elif fault == "receipt":
        owner["callback_receipts"][-1]["intent_count"] = True
    elif fault == "outer-cursor":
        state = replace(state, bar_index=1)
    elif fault == "outer-config":
        state = replace(state, config_snapshot_hash="f" * 64)
    elif fault == "external-runtime":
        state = replace(state, runtime_state={"foreign": True})
    elif fault == "accounting":
        state = replace(
            state, broker_state=replace(state.broker_state, cash=state.broker_state.cash + 1)
        )
    else:
        raise AssertionError(fault)
    reseal(owner, receipts=fault == "receipt")
    return state


@pytest.mark.parametrize(
    "fault",
    [
        "identity",
        "na",
        "refgraph",
        "request",
        "transcript",
        "receipt",
        "outer-cursor",
        "outer-config",
        "external-runtime",
        "accounting",
    ],
)
def test_bad_bytes_preserve_engine_owner_and_effect_receivers(
    compiled_descriptor, wire, fault, monkeypatch
):
    state = JsonResumeStateSerializer().loads(wire)
    state = mutate(state, fault)
    # The engine codec still admits plain foreign graph data; the generated
    # owner must reject it. Typed/accounting faults may be rejected by dumps.
    try:
        bad = JsonResumeStateSerializer().dumps(state)
    except ResumeUnsupportedError:
        envelope = json.loads(wire)
        if fault == "outer-cursor":
            envelope["state"]["fields"]["bar_index"] = 1
        elif fault == "accounting":
            envelope["state"]["fields"]["broker_state"]["fields"]["cash"] += 1
        else:
            raise
        bad = canonical_json(envelope)
    config, bars = inputs()
    owner, engine = session(compiled_descriptor, config), BacktestEngine(config)
    # Leave actual previously committed owner/broker state in the receiver.
    run_generated_backtest(engine, owner, bars)
    before_owner, before_engine = owner.export_state(), projection(engine)
    identities = (
        engine.position,
        engine.orders,
        engine.fills,
        engine.state,
        engine.events,
        engine.warnings,
        engine.errors,
        owner.session,
        owner.execution_cursor,
        owner._callback_receipts,
        owner.session.series,
        owner.session.slots,
        owner.session.references,
        owner.session.requests,
        owner.session.transcript,
    )
    calls, tape = [], []
    callbacks = BacktestCallbacks(
        on_fill=lambda fill: calls.append(fill),
        on_bar_start=lambda *args: calls.append(args),
    )

    def forbidden_reset():
        raise AssertionError("invalid bytes reached live broker reset")

    def forbidden_fetch(*args, **kwargs):
        calls.append("provider-fetch")
        raise AssertionError("invalid bytes fetched request data")

    def forbidden_evaluate(*args, **kwargs):
        calls.append("generated-evaluation")
        raise AssertionError("invalid bytes evaluated generated code")

    monkeypatch.setattr(engine, "_reset_state", forbidden_reset)
    monkeypatch.setattr(type(owner.session.requests.provider), "fetch", forbidden_fetch)
    monkeypatch.setattr(owner.generated_class, "run", forbidden_evaluate)
    with pytest.raises(ResumeUnsupportedError):
        run_generated_backtest(
            engine, owner, bars, resume_state=bad, callbacks=callbacks, tape_events=tape
        )
    assert owner.export_state() == before_owner and projection(engine) == before_engine
    assert all(
        a is b
        for a, b in zip(
            identities,
            (
                engine.position,
                engine.orders,
                engine.fills,
                engine.state,
                engine.events,
                engine.warnings,
                engine.errors,
                owner.session,
                owner.execution_cursor,
                owner._callback_receipts,
                owner.session.series,
                owner.session.slots,
                owner.session.references,
                owner.session.requests,
                owner.session.transcript,
            ),
        )
    )
    assert calls == [] and tape == []


def test_valid_generated_graph_cannot_be_spliced_onto_another_broker_boundary(
    compiled_descriptor, wire, monkeypatch
):
    config, bars = inputs()
    ahead = session(compiled_descriptor, config)
    run_generated_backtest(BacktestEngine(config), ahead, bars, resume_state=wire)
    state = replace(JsonResumeStateSerializer().loads(wire), strategy_state=ahead.export_state())
    bad = JsonResumeStateSerializer().dumps(state)
    owner, engine = session(compiled_descriptor, config), BacktestEngine(config)
    before = owner.export_state()
    monkeypatch.setattr(
        engine, "_reset_state", lambda: pytest.fail("boundary check must precede reset")
    )
    with pytest.raises(ResumeUnsupportedError, match="committed boundary differ"):
        run_generated_backtest(engine, owner, bars, resume_state=bad)
    assert owner.export_state() == before


def test_late_preflight_failure_precedes_reset_and_preserves_decoded_input(
    compiled_descriptor, wire, monkeypatch
):
    config, bars = inputs()
    owner, engine = session(compiled_descriptor, config), BacktestEngine(config)
    before = owner.export_state()

    def corrupt_late(state):
        state["runtime"]["state"]["references"]["objects"][0]["committed"].append(999)
        raise ValueError("late failure")

    monkeypatch.setattr(owner, "prepare_restore", corrupt_late)
    monkeypatch.setattr(engine, "_reset_state", lambda: pytest.fail("preflight must precede reset"))
    with pytest.raises(ResumeUnsupportedError, match="late failure"):
        run_generated_backtest(engine, owner, bars, resume_state=wire)
    assert owner.export_state() == before
    assert (
        len(
            JsonResumeStateSerializer()
            .loads(wire)
            .strategy_state["runtime"]["state"]["references"]["objects"][0]["committed"]
        )
        == 1
    )


def process(mode, folder):
    folder = Path(folder)
    if mode == "producer":
        data = descriptor()
        wire, tape = producer(data)
        (folder / "descriptor.json").write_bytes(canonical_json(data))
        (folder / "checkpoint.json").write_bytes(wire)
        report = {
            "pid": os.getpid(),
            "pins": data["pins"],
            "wire_bytes": len(wire),
            "prefix": [[row["command_id"], row["qty"], row["bar_index"]] for row in tape],
            "artifact_hash": data["artifact"]["generated_artifact"]["content_hash"],
            "passed": True,
        }
    else:
        data = json.loads((folder / "descriptor.json").read_bytes())
        config, bars = inputs()
        engine, owner, tape = BacktestEngine(config), session(data, config), []
        run_generated_backtest(
            engine,
            owner,
            bars,
            resume_state=(folder / "checkpoint.json").read_bytes(),
            tape_events=tape,
        )
        literal_oracle(engine, tape)
        control_config = replace(config, early_stop_enabled=False)
        control, whole = BacktestEngine(control_config), session(data, control_config)
        run_generated_backtest(control, whole, bars)
        assert projection(engine) == projection(control)
        assert owner.session.semantic_state_hash == whole.session.semantic_state_hash
        report = {
            "pid": os.getpid(),
            "pins": data["pins"],
            "effects": projection(engine),
            "suffix": [[row["command_id"], row["qty"], row["bar_index"]] for row in tape],
            "independent_literal_oracle": True,
            "public_control_agrees": True,
            "source_overlay": True,
            "passed": True,
        }
    (folder / (mode + ".json")).write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report))


def test_exporter_exits_before_independent_public_bytes_consumer(tmp_path):
    outcomes = []
    for mode in ("producer", "consumer"):
        result = subprocess.run(  # noqa: S603 -- fixed interpreter and this test module; only output directory varies
            [sys.executable, "-B", __file__, mode, str(tmp_path)],
            text=True,
            capture_output=True,
        )
        assert result.returncode == 0, result.stdout + result.stderr
        outcomes.append(json.loads((tmp_path / (mode + ".json")).read_text()))
    assert outcomes[0]["pid"] != outcomes[1]["pid"]
    assert all(result["passed"] for result in outcomes)


if __name__ == "__main__":
    process(sys.argv[1], sys.argv[2])
