"""Frozen manual corpus through real Pine+broker, not expected generated by the SUT."""

import json
import os
from dataclasses import replace
from pathlib import Path

import pytest
from openpine.verification.conformance import compare_corpus, load_corpus
from openpine.verification.identity import write_json
from rc6_tests.test_rc6_bulk_execution import bulk_case
from rc6_tests.test_rc6_lifecycle import compile_case
from rc6_tests.test_rc6_deferred_exits import compare_modes
from rc6_tests.test_rc6_marketdata_boundary import OPENED, bar

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "verification/corpus-v1/manifest.json"
MANIFEST = load_corpus(PATH)
LOCK = json.loads((ROOT / "verification/corpus-lock.json").read_text())["content_hash"]


@pytest.mark.parametrize("case", MANIFEST["cases"], ids=lambda c: c["id"])
def test_frozen_pine_corpus_both_transports(monkeypatch, tmp_path, case):
    source = (PATH.parent / case["source"]["path"]).read_text()
    compiled, context, config = compile_case(bulk_case.__wrapped__(), source)
    settings = json.loads((PATH.parent / case["settings"]["path"]).read_text())
    rows = json.loads((PATH.parent / case["data"]["path"]).read_text())
    config = replace(config, **settings)
    candles = [
        bar(open_time_utc_ms=OPENED + i * 60000, open=a, high=b, low=c, close=d)
        for i, (a, b, c, d) in enumerate(rows)
    ]
    result, tape = compare_modes(monkeypatch, tmp_path, (compiled, context, config), candles)
    events = [
        {
            "kind": event["kind"],
            "bar": event["bar_index"],
            "phase": event["phase"],
            "id": event["command_id"],
            "qty": float(event["qty"]),
            "source_span": {"start_line": event["source_span"]["start_line"]},
        }
        for event in tape
    ]
    events.extend(
        {
            "kind": "open_trade",
            "bar": trade.entry_bar_index,
            "phase": "BROKER_FILL",
            "entry_price": trade.entry_price,
            "qty": trade.qty,
        }
        for trade in result.open_trades
    )
    observed = {
        "status": "completed",
        "compile": compiled.success,
        "events": events,
        **{key + "_sha256": case[key]["sha256"] for key in ("source", "data", "settings")},
    }
    report = compare_corpus(PATH, {case["id"]: observed}, expected_corpus_hash=LOCK)
    own = next(row for row in report["results"] if row["id"] == case["id"])
    assert own["status"] == "PASS", own
    assert not report["tradingview_verified"]
    if output := os.environ.get("OPENPINE_STAGE1_EVIDENCE"):
        write_json(Path(output) / "observations" / (case["id"] + ".json"), observed)


@pytest.mark.parametrize("mode", ["interactive", "bulk_backtest"])
def test_real_worker_exports_matching_effective_config_receipt(tmp_path, mode):
    from openpine.runtime.isolated_run import run_isolated_artifact
    from openpine.runtime.rc6_worker_runtime import _engine_bar
    from openpine.runtime.rc6_config import resolve_engine_config, serialize_engine_config
    from rc6_tests.test_rc6_worker_admission import _manifest

    case = next(
        c for c in MANIFEST["cases"] if c["pine_version"] == 6 and "no-entry" not in c["id"]
    )
    compiled, context, config = compile_case(
        bulk_case.__wrapped__(), (PATH.parent / case["source"]["path"]).read_text()
    )
    settings = json.loads((PATH.parent / case["settings"]["path"]).read_text())
    config = replace(config, **settings)
    candles = [
        bar(open_time_utc_ms=OPENED + i * 60000, open=a, high=b, low=c, close=d)
        for i, (a, b, c, d) in enumerate(
            json.loads((PATH.parent / case["data"]["path"]).read_text())
        )
    ]
    expected = resolve_engine_config(serialize_engine_config(config, "strict_5x"), context)
    for name, value in dict(
        execution_context=context,
        admitted_manifest=_manifest(),
        instrument_id=context["instrument_id"],
        generated_artifact=compiled.generated_artifact,
        bar_envelopes=candles,
        run_hash="sha256:" + "1" * 64,
        protocol_artifact_dir=str(tmp_path / "protocol"),
        isolated_protocol=mode,
    ).items():
        setattr(config, name, value)
    output = run_isolated_artifact(
        compiled.python_code.encode(),
        bars=[_engine_bar(b) for b in candles],
        config=config,
        params={},
    )
    assert output["ok"]
    result = output["raw_result"]
    receipt = (
        result["effective_config_evidence"]
        if isinstance(result, dict)
        else result.effective_config_evidence
    )
    # Bulk's established hydrator uses attribute objects recursively; normalize
    # representation only, retaining exact receipt values and all assertions.
    from types import SimpleNamespace

    def plain(value):
        if isinstance(value, SimpleNamespace):
            value = vars(value)
        if isinstance(value, dict):
            return {key: plain(item) for key, item in value.items()}
        if isinstance(value, list):
            return [plain(item) for item in value]
        return value

    receipt = plain(receipt)
    assert receipt["settings_hash"] == expected.effective_config_hash
    assert receipt["provenance"]["mintick"][-1] in {"admitted_instrument", "engine_normalization"}
    assert receipt["upstream_provenance"] == "unresolved_before_admission"
