"""Concrete generated-script bytes bridge over existing broker and checkpoint owners."""

from __future__ import annotations

from copy import copy
from dataclasses import replace
from typing import Any, TYPE_CHECKING

from backtest_engine import BacktestEngine, JsonResumeStateSerializer
from backtest_engine.core.engine_realtime import config_snapshot_hash
from backtest_engine.core.engine_validation import validate_backtest_config
from backtest_engine.core.resume_json import admit_resume_input
from backtest_engine.core.score_window import build_score_window_plan
from backtest_engine.core.strategy_capabilities import strategy_values_from_state
from backtest_engine.core.validation import infer_price_tick, validate_bars
from backtest_engine.errors import ResumeUnsupportedError
from backtest_engine.models import BacktestCallbacks, Bar, BarSeries
from backtest_engine.results import BacktestResult
from openpine_contracts import ExecutionEvent
from pinelib.runtime.metadata import BarValues

from openpine.runtime.rc6_config import serialize_engine_config

if TYPE_CHECKING:
    from openpine.runtime.rc6_worker_runtime import RC6GeneratedScriptSession


def generated_strategy(
    session: RC6GeneratedScriptSession,
    tape_events: list[dict[str, Any]],
    *,
    engine: BacktestEngine | None = None,
) -> type:
    """Share the existing bulk callback/intent adapter with the bytes bridge."""
    from backtest_engine.core.intent_replay import (
        admit_sealed_intent_tape,
        apply_live_intents_for_bar,
    )

    class _GeneratedStrategy:
        required_runtime_capabilities: tuple[str, ...] = ()

        def __init__(self, params: dict[str, Any], runtime: Any, ctx: Any) -> None:
            del runtime
            if params != dict(session.inputs.values):
                raise ValueError("bulk broker parameters differ from applied Pine inputs")
            self.ctx = ctx

        def run_callback(self, bar: Any, event: ExecutionEvent) -> None:
            values = BarValues(
                open=float(bar.open),
                high=float(bar.high),
                low=float(bar.low),
                close=float(bar.close),
                volume=float(bar.volume or 0),
                time=int(bar.time),
                time_close=int(bar.time_close or bar.time),
            )
            execution = session.execute_callback(
                values,
                event,
                strategy_values=strategy_values_from_state(self.ctx.state, self.ctx.config),
                open_entry_ids=tuple(trade.entry_id for trade in self.ctx.state._open_trades_ref),
                broker_equity=self.ctx.state.equity,
            )
            batch = [dict(intent) for intent in execution.intents]
            tape_events.extend(batch)
            if batch:
                current = admit_sealed_intent_tape(batch, sequence_origin=int(batch[0]["sequence"]))
                apply_live_intents_for_bar(
                    self.ctx,
                    current,
                    event.bar_index,
                    bar_open_time_utc_ms=int(bar.time),
                )

        def export_state(self) -> dict[str, Any]:
            return session.export_state()

        def restore_state(self, state: Any) -> None:
            session.restore_state(state)
            # The generated owner proves this sequence through callback receipts.
            # Resume the broker's event producer at that same committed boundary.
            if engine is not None:
                last = session.execution_cursor.last
                engine._execution_callback_sequence = -1 if last is None else last.sequence

    return _GeneratedStrategy


def run_generated_backtest(
    engine: BacktestEngine,
    session: RC6GeneratedScriptSession,
    bars: BarSeries | list[Bar],
    *,
    resume_state: bytes | None = None,
    callbacks: BacktestCallbacks | None = None,
    tape_events: list[dict[str, Any]] | None = None,
) -> BacktestResult:
    """Run an admitted RC6 session, including a committed historical bytes resume.

    The engine codec owns the typed broker envelope; the generated owner owns
    its complete strategy graph. Both are admitted before live reset or restore.
    This is an in-process source/API bridge, not protected-worker qualification.
    """
    from openpine.runtime.rc6_worker_runtime import RC6GeneratedScriptSession

    if not isinstance(session, RC6GeneratedScriptSession):
        raise ResumeUnsupportedError("generated bytes bridge requires an RC6 session")
    config = engine.config
    if (
        config.resume_validation_policy != "strict"
        or config.calc_on_every_tick
        or config.runtime is not None
        or config.warmup_policy
        or config.force_close_on_end
    ):
        raise ResumeUnsupportedError(
            "generated bytes bridge requires strict historical bars, no external runtime, "
            "warmup or forced final close"
        )
    admission_config = copy(config)
    validate_backtest_config(admission_config)
    profile = session.identity.semantic_profile
    if serialize_engine_config(admission_config, profile) != serialize_engine_config(
        session.intent_config, profile
    ):
        raise ResumeUnsupportedError("generated session engine config differs from broker config")
    selected = engine._resolve_bars(bars)
    series = engine._slice_range(selected)
    plan = build_score_window_plan(
        series_len=len(series),
        score_start_time=config.score_start_time,
        score_end_time=config.score_end_time,
        effective_pre_bars=None,
    )
    if config.validate_bars:
        series, _ = validate_bars(series, config.duplicate_bar_policy)

    state = None
    if resume_state is not None:
        state = JsonResumeStateSerializer().loads(resume_state)
        if (
            state.runtime_state is not None
            or "realtime_tick_schedule_fingerprint" in state.metadata
        ):
            raise ResumeUnsupportedError(
                "generated bytes bridge has no external/tick runtime owner"
            )
        admit_resume_input(
            state,
            admission_config,
            config_snapshot_hash(admission_config),
            series,
            plan,
            mark_tick=config.mintick or infer_price_tick(selected),
        )
        if state.bar_index < 0 or not isinstance(state.strategy_state, dict):
            raise ResumeUnsupportedError(
                "generated bytes resume requires a committed strategy checkpoint"
            )
        try:
            prepared = session.prepare_restore(state.strategy_state)
        except Exception as error:
            raise ResumeUnsupportedError(
                "generated owner preflight failed: " + str(error)
            ) from error
        last = prepared.cursor.last
        bar = series.get_bar(state.bar_index)
        if (
            last is None
            or last.realtime
            or not last.final_tick
            or last.bar_index != state.bar_index
            or last.bar_open_time_utc_ms != int(bar.time)
            or last.last_bar_index != len(series) - 1
            or last.last_historical_bar_index != len(series) - 1
        ):
            raise ResumeUnsupportedError(
                "generated checkpoint and broker committed boundary differ"
            )

    owner_callbacks = copy(callbacks) if callbacks is not None else BacktestCallbacks()
    on_bar_end = owner_callbacks.on_bar_end or (owner_callbacks.extra or {}).get("on_bar_end")

    def finalize(bar: Bar, index: int, state_view: object) -> None:
        session.finalize_bar(index)
        if on_bar_end is not None:
            on_bar_end(bar, index, state_view)

    owner_callbacks = replace(owner_callbacks, on_bar_end=finalize)
    events = tape_events if tape_events is not None else []
    # Existing restore_state re-admits the frozen decoded graph under the same
    # owner before its atomic replacement; no alternate decoder or schema lives here.
    return engine.run(
        generated_strategy(session, events, engine=engine),
        params=dict(session.inputs.values),
        bars=selected,
        callbacks=owner_callbacks,
        resume_state=state,
    )
