#!/usr/bin/env python3
"""Render the badge block used at the top of every OpenPine-stack README.

Each badge is wrapped in a clickable <a> that points at the target repository
or release page. The block returned by :func:`render_block` is the single
source of truth — every ``README.md`` in the 7-repo stack is generated by
calling this script so that badge labels, versions, and links stay in lock
step.

Usage::

    python scripts/render_badges.py --repo openpine
    python scripts/render_badges.py --repo pine2ast --emit
    python scripts/render_badges.py --emit --out README.badges.md
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence

ORG = "s7cret"

# Repo slug → display label / target.
# Repos use underscores in the GitHub slug even if the package uses
# dashes. Keep this mapping exact.
_REPO_TARGETS: dict[str, str] = {
    "openpine": "https://github.com/s7cret/openpine",
    "pine2ast": "https://github.com/s7cret/pine2ast",
    "ast2python": "https://github.com/s7cret/ast2python",
    "pinelib": "https://github.com/s7cret/pinelib",
    "marketdata-provider": "https://github.com/s7cret/marketdata-provider",
    "backtest_engine": "https://github.com/s7cret/backtest_engine",
    "optimizer": "https://github.com/s7cret/optimizer",
}


@dataclass(frozen=True)
class Badge:
    label: str  # shields.io slug, e.g. "version-4.0.0-blue"
    alt: str    # accessible alt text for the image

    @property
    def src(self) -> str:
        return f"https://img.shields.io/badge/{self.label}"

    def to_markdown(self, href: str) -> str:
        return f"[![{self.alt}]({self.src})]({href})"


# Common top-of-README badges (Version / Python / License).
def common_badges(version: str, min_python: str) -> Sequence[Badge]:
    return (
        Badge(f"version-{version}-blue", "Version"),
        Badge(f"python-%3E%3D{min_python}-blue", "Python"),
        Badge("license-MIT-green", "License"),
    )


# Stack cross-links — used by the central ``openpine`` README so readers
# can jump straight to the related libraries in the same organization.
STACK = (
    ("Pine2AST", "pine2ast"),
    ("AST2Python", "ast2python"),
    ("PineLib", "pinelib"),
    ("Backtest Engine", "backtest_engine"),
    ("MarketData Provider", "marketdata-provider"),
    ("Optimizer", "optimizer"),
)


def stack_badges(version: str) -> Sequence[Badge]:
    return tuple(
        Badge(f"{slug.replace('-', '_') if slug != 'marketdata-provider' else 'marketdata_provider'}-{version}-blue", label)
        for label, slug in STACK
    )


def render_block(repo: str, version: str = "4.0.0", min_python: str = "3.11") -> str:
    """Return the markdown badge block for a single repo.

    The block is plain markdown wrapped in HTML anchors so each badge is
    a clickable link. No script or stylesheet dependencies.
    """
    if repo not in _REPO_TARGETS:
        raise ValueError(f"unknown repo: {repo!r}")
    target = _REPO_TARGETS[repo]
    parts: list[str] = []
    for badge in common_badges(version, min_python):
        parts.append(badge.to_markdown(target))
    if repo == "openpine":
        # Central repo: cross-link to the six sister libraries.
        for label, slug in STACK:
            stack_badge = Badge(
                f"{slug.replace('-', '_')}-{version}-blue", label
            )
            parts.append(stack_badge.to_markdown(_REPO_TARGETS[slug]))
    return " ".join(parts)


def replace_block(readme: str, repo: str, version: str, min_python: str) -> str:
    """Replace the existing badge block (if any) with a freshly rendered one.

    The block is identified as the leading contiguous run of ``![...](shields.io...)``
    lines immediately after the first ``#`` heading. The first such run is
    replaced with the output of :func:`render_block`. The rest of the README
    is preserved verbatim.
    """
    lines = readme.splitlines()
    block_start: int | None = None
    block_end: int = 0
    for idx, line in enumerate(lines):
        if "img.shields.io/badge/" in line:
            if block_start is None:
                block_start = idx
            block_end = idx + 1
        elif block_start is not None:
            break
    new_block = render_block(repo, version=version, min_python=min_python)
    if block_start is None:
        # No existing badge block — insert immediately after the first H1.
        for idx, line in enumerate(lines):
            if line.startswith("# "):
                return "\n".join(lines[: idx + 1] + ["", new_block, ""] + lines[idx + 1 :])
        return new_block + "\n\n" + readme
    return "\n".join(lines[:block_start] + [new_block, ""] + lines[block_end:])


def patch_readme(path: Path, repo: str, version: str, min_python: str) -> bool:
    text = path.read_text(encoding="utf-8")
    new_text = replace_block(text, repo, version, min_python)
    if new_text == text:
        return False
    path.write_text(new_text, encoding="utf-8")
    return True


def _repos_for_path(path: Path) -> Iterable[str]:
    """Best-effort mapping from a README path to a repo slug."""
    parts = path.parts
    for slug in _REPO_TARGETS:
        if slug in parts:
            yield slug


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", choices=sorted(_REPO_TARGETS), required=True)
    parser.add_argument("--version", default="4.0.0")
    parser.add_argument("--min-python", default="3.11")
    parser.add_argument(
        "--readme",
        type=Path,
        default=None,
        help="Path to README.md (default: <repo-root>/README.md).",
    )
    parser.add_argument(
        "--emit",
        action="store_true",
        help="Print the rendered block to stdout instead of patching a file.",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Optional output path (only used together with --emit).",
    )
    args = parser.parse_args(argv)

    if args.emit:
        block = render_block(args.repo, version=args.version, min_python=args.min_python)
        if args.out is not None:
            args.out.write_text(block + "\n", encoding="utf-8")
        else:
            sys.stdout.write(block + "\n")
        return 0

    if args.readme is None:
        # Resolve default location: ~/openpine/<repo>/README.md for the 6
        # libraries, ~/openpine/openpine/README.md for the central repo.
        root = Path("/home/moltbot1/openpine" if args.repo != "openpine" else "/home/moltbot1/.openclaw/workspace/openpine")
        readme = root / "README.md"
    else:
        readme = args.readme
    if not readme.exists():
        sys.stderr.write(f"README not found: {readme}\n")
        return 1
    changed = patch_readme(readme, args.repo, args.version, args.min_python)
    sys.stdout.write(f"{'updated' if changed else 'unchanged'}: {readme}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
